# Generated by Django 2.0.5 on 2018-05-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
    ]
