# Generated by Django 2.0.5 on 2018-05-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180524_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='gx', max_length=20, verbose_name='机构类别'),
        ),
    ]
