# Generated by Django 2.0.5 on 2018-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告知'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='course/image/%Y/%m/%d', verbose_name='课程封面'),
        ),
    ]
